### ISSUE TITLE
RotationLock makes the library essentially single-threaded

### ISSUE THREAD

**Issue by edyoung** [satmihir/fair#5]
It's possible I have misunderstood something. Apologies if so!

Because rotationlock is held through the entire time that ReportOutcome and RegisterRequest are running, only one thread can update the fairness tracker at a time. While in a real system a small fraction of the time should be spent checking the throttling state, this could become increasingly expensive if a lot of concurrent lookups are happening.

I don't have an exact solution, but I think that if it's possible to accept updates going to the wrong structure occasionally, the lock may not be required at all. 

Expanding on this a bit, we have a race between the goroutine switching the structures, and goroutines performing updates (the rotation lock is not needed to prevent 2 updates from running in parallel). The state updated by the rotation visible to other threads is

Main=A, Secondary=B
Main=B, Secondary=B
Main=B, Secondary=C (the newly-created structure)

If the update threads can operate safely on the intermediate states while the rotation changes are happening, the lock is not needed. 
The update thread might operate on (A,B), (A, C), (B, B), or (B, C).

(A,B) and (B,C) are normal. 
(A,C) means the first half of the update is lost, but that was going to happen anyway once the rotation completed
(B,B) means the update happens twice, which does potentially mean the calculation is wrong, but I think in quite a minor way (we record 2 successful or failed operations rather than 1).

**Comment by satmihir** [comment]
Ah thanks for reporting. I did make a mental note when writing that code but never got around to it. Thanks for paying attention! All we really need is atomic updates which doesn't really need locks. I will address this in a day or so. Thanks again!

**Comment by satmihir** [comment]
This addresses the issue using RWLocks https://github.com/satmihir/fair/pull/6

I'll try to implement an atomic.Value based solution soon.

**Comment by satmihir** [comment]
By the way @edyoung - since you are taking a look at the code, would you like to be added as a contributor?

**Comment by satmihir** [comment]
No worries. Thanks for your contributions!

**Comment by satmihir** [comment]
@edyoung Did you end up using FAIR to implement your use case? Looking for some feedback if you are open.

**Comment by edyoung** [comment]
No, I haven't deployed anything in production. I was looking out of interest rather than immediate implementation.

**Comment by satmihir** [comment]
@edyoung thanks. If you are okay with it, I'd like to connect and briefly chat about your experience studying/evaluating the library. If you are okay to do it, please accept my LinkedIn invite or suggest an alternative way to connect :)
